name: Pull Request Template
description: Template for submitting pull requests to the Block Accessibility Checks plugin.
labels: ['enhancement']
body:
    - type: textarea
      attributes:
          label: Description
          description: Provide a detailed description of the changes made in this pull request.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Related Issue
          description: If applicable link to the issue that this pull request aims to solve.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Testing Instructions
          description: Provide step-by-step instructions on how to test the changes made in this pull request.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots or Recordings
          description: Provide any relevant screenshots or recordings to help understand the changes.
      validations:
          required: false

    - type: checkboxes
      attributes:
          label: Have you added a note to the changelog?
          description: If you have not, please add a note to the changelog.
          options:
              - label: 'Yes, I have updated the changelog.'
                required: true
