name: Task
description: Make a note of something that needs to be done
labels: ['task']
body:
    - type: textarea
      attributes:
          label: Description
          description: Provide a more detailed explanation of what the feature should do and why it would be useful. Include any specific requirements or criteria that should be met.
      validations:
          required: true
